config/routes.rb
Rails.application.routes.draw do
  resources :recordings, only: [:new, :create]
  resources :parts, only: :index

  root to: redirect("/recordings/new")
end

app/models/application_model.rb
class ApplicationModel
  include ActiveModel::Model
  include ActiveModel::Attributes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/identification.rb
class Identification
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :artist, :string
  attribute :song, :string
end

app/models/part.rb
class Part < ApplicationModel
  attribute :video, :string
  attribute :name, :string
end

app/models/parts/search.rb
class Parts::Search < ApplicationModel
  attribute :cache, default: {}
  attribute :song

  def results
    cache.fetch(search_url) do
      response = JSON.parse(URI.parse(search_url).read, symbolize_names: true)

      response.fetch(:song_results, []).flat_map do |search_result|
        video = search_result.fetch(:title)

        search_result.fetch(:soundtracks, []).map do |soundtrack|
          name = soundtrack.fetch(:section)

          Part.new(video:, name:)
        end
      end
    end
  end

  private

  def search_text
    [song.artist, song.name].join(" ").squish.downcase.gsub(/[^[:word:]\s]/i, "")
  end

  def search_url
    "https://skatevideosite.com/api/search?" + {search_text:}.to_query
  end
end

app/models/song.rb
class Song < ApplicationModel
  PARENTHESIZED_PHRASES = /(\[|\().*(\]|\))/

  attribute :artist, :string
  attribute :name, :string
  attribute :cache, default: {}

  def parts
    Parts::Search.new(song: self, cache:).results
  end

  def name
    super
      .gsub(PARENTHESIZED_PHRASES, "")
      .squish
      .strip
  end
end

app/models/song_search.rb
class SongSearch < ApplicationModel
  Result = Data.define(:video, :part)

  attribute :cache, default: {}
  attribute :song

  def results
    cache.fetch(search_url) do
      response = JSON.parse(URI.parse(search_url).read, symbolize_names: true)

      response.fetch(:song_results, []).flat_map do |search_result|
        video = search_result.fetch(:title)

        search_result.fetch(:soundtracks, []).map do |soundtrack|
          Result.new(video, soundtrack.fetch(:section))
        end
      end
    end
  end

  private

  def search_text
    [song.artist, song.name].join(" ").squish.downcase.gsub(/[^[:word:]\s]/i, "")
  end

  def search_url
    "https://skatevideosite.com/api/search?" + {search_text:}.to_query
  end
end

app/models/unknown_song.rb
class UnknownSong
  include ActiveModel::Conversion

  def artist
    ""
  end

  def name
    ""
  end

  def parts
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  def create
    tui = redirect_params.delete(:tui).presence || -1

    redirect_to song_url(tui, params: redirect_params)
  end

  private

  def redirect_params
    params.require(:identification).permit(
      :artist,
      :name,
      :tui,
    )
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
    @song = Song.new name: params[:title], artist: params[:artist], cache: Rails.cache
  end
end

app/controllers/recordings_controller.rb
require "net/http"

class RecordingsController < ApplicationController
  def create
    result = audd_response[:result]

    if result
      redirect_to parts_url(result.slice(:artist, :title))
    else
      head 422
    end
  end

  private

  def audd_response
    endpoint = URI("https://api.audd.io")

    post = Net::HTTP::Post.new(endpoint)
    post.set_form(recording_params.to_h.to_a, "multipart/form-data")

    http_response = Net::HTTP.start(endpoint.hostname, endpoint.port, use_ssl: true) { |http| http.request(post) }

    JSON.parse(http_response.body, symbolize_names: true)
  end

  def recording_params
    params.permit(:return, :file)
      .rewrite(:file) { |file| file&.open }
      .merge(api_token: Rails.configuration.x.audd.api_token)
      .compact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

    <title>Gripthumb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="manifest" href="/site.webmanifest"></link>

    <%= stylesheet_link_tag "tailwind", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="flex flex-col min-h-screen">
    <header class="fixed h-11 bg-white flex items-center px-4 border-b-2 pt-safe-top w-full">
      <%= link_to new_recording_path, class: "font-mono font-bold text-2xl" do %>
        gripthumb
      <% end %>
    </header>

    <main class="flex flex-col flex-grow mt-11 pt-safe-top">
      <%= yield %>
    </main>
  </body>
</html>

app/views/parts/_part.html.erb
<article class="p-4">
  <span class="font-bold text-2xl"><%= part.name %></span>
  <span class="font-semibold text-lg"><%= part.video %></span>
</article>

app/views/parts/index.html.erb
<header class="flex justify-center border-b-2 p-4">
  <h1 class="text-center">
    <p class="font-sembold text-4xl"><%= @song.name %></p>
    <p class="font-bold text-3xl"><%= @song.artist %></p>
  </h1>
</header>

<section class="divide-y-2">
  <%= render(@song.parts) || render("songs/empty") %>
</section>

<section class="fixed bottom-0 flex self-center items-center">
  <%= render "recordings/form" %>
</section>

app/views/recordings/_form.html.erb
<section id="recorder" class="flex flex-col items-center">
  <form action="<%= recordings_path %>" method="post" enctype="multipart/form-data" data-controller="recording" data-action="turbo:before-fetch-response->recording#presentError">
    <h2 class="font-semibold text-2xl text-center" data-recording-target="error" hidden>Try again</h2>

    <input type="hidden" name="return" value="apple_music,spotify">

    <progress class="peer sr-only" data-recording-target="progress" value="0"></progress>

    <button type="button" class="rounded-full bg-black border-8 w-48 h-48 mt-4 peer-indeterminate:border-black peer-indeterminate:bg-red-600" data-action="click->recording#start">
      <span class="sr-only">Recognize song</span>
    </button>

    <fieldset <%= tag.attributes hidden: !Rails.env.test? %>>
      <label for="file">File</label>
      <input type="file" id="file" name="file">
      <button type="submit">Submit</button>
    </fieldset>
  </form>
</section>

app/views/recordings/new.html.erb
<section class="flex self-center flex-grow items-center">
  <%= render "recordings/form" %>
</section>

app/views/songs/_empty.html.erb
<article class="p-4">
  <span class="font-bold text-2xl">We couldn't find any parts to this song.</span>
</article>

app/views/unknown_songs/_unknown_song.html.erb
<header>
  <p><%= t(".title") %></p>
</header>

<ul class="parts">
</ul>